### ISSUE TITLE
Console Error when reloading plugin...config gets resetted

### ISSUE THREAD

**Issue by Chris6ix** [ChestsPlusPlus/ChestsPlusPlus#79]
When i do `/chests++ reload` the config resets to default and this Error is in the console:
(Tested on a clean 1.18.2 Paper #283 Server)

[ChestsPlusPlus] Task #245 for ChestsPlusPlus v2.6 generated an exception
java.lang.StackOverflowError: null
        at java.lang.String.valueOf(String.java:4215) ~[?:?]
        at java.lang.StringBuilder.append(StringBuilder.java:173) ~[?:?]
        at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[snakeyaml-1.30.jar:?]
        
It repeats the last part of that Error like 100 times...I shortened it as it's unnecessary

**Comment by Clashbestie** [comment]
The Methode causing the error seems to be missing. I suggest that you put the full error on pastebin.

**Comment by Chris6ix** [comment]
I don't have the full log anymore, and I abandoned the idea of using this plugin quite some time ago because it's missing some features that are essential to me (#78 and #80) so I'm going to close this as this could be caused by the fact that the version I used isn't 1.18.2 compatible and was just overall very broken on 1.18.2. (#77)
If the plugin gets updated sometime with the features I need, then I'm going to check it out again...if that version still has this problem, then I'm re-opening this issue/creating a new one.

Thanks anyway :)
